import sys
import os
os.system("title Debug")
if len(sys.argv) > 1:
    var = (sys.argv[1])
else:
    print("Error.\nsys.argv[1] not defined.\nThe program has been run with a double click and not through the protocol.")
    os.system("echo Press any key to exit... && pause > nul && exit")
print("Program called with argument:")
print(sys.argv[1])
var = (sys.argv[1])
var = (var[8:])
var1 = var[-1]
if var == "/":
    print("Converted Argument:")
    print("cmd")
    os.system("echo.")
    os.system("title Command Prompt")
    os.system("echo Press any key to exit && pause > nul")
if var1 == "/":
    var = (var[0:-1])
os.system("echo.")
var = (var).replace ("%20", " ")
var = (var).replace ("%5C", "\\")
var = (var).replace ("%22", '"')
var = (var).replace ("%25", '%')
var = (var).replace ("%3C", '<')
var = (var).replace ("%3E", '>')
var = (var).replace ("%23", '#')
var = (var).replace ("%7C", '|')
var = (var).replace ("%7B", '{')
var = (var).replace ("%7D", '}')
var = (var).replace ("%5E", '^')
var = (var).replace ("%7E", '~')
var = (var).replace ("%5B", '[')
var = (var).replace ("%5D", ']')
var = (var).replace ("%60", '`')
print("Converted Argument:")
print(var)
os.system("echo.")
os.system("echo Press any key to exit && pause > nul")